### ISSUE TITLE
Error: already loaded plugin named:private

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/ssb-private#3]
tried installing this `scuttlebot` plugin, to use for ssb-bot

[%2JaltAdhcWnJwOXJPbHvGE9+SlVrR7Vfq+RhJbMhVUM=.sha256](https://viewer.scuttlebot.io/%252JaltAdhcWnJwOXJPbHvGE9%2BSlVrR7Vfq%2BRhJbMhVUM%3D.sha256)

but this conflicts with the default `private` plugin? is there a workaround for this?

```
➜  ssb-bot git:(master) ✗ ssb_appname="ssb-bot" sbot server
scuttlebot 10.5.0 /home/dinosaur/.ssb-bot logging.level:notice
my key ID: OQExQgTAHrs+iMj5kbx1AEgrRTP9DnGXM1ngNfqJLWc=.ed25519
/home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/scuttlebot/plugins/plugins.js:184
      throw new Error('already loaded plugin named:'+name)
      ^

Error: already loaded plugin named:private
    at Object.module.exports.loadUserPlugins (/home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/scuttlebot/plugins/plugins.js:184:13)
    at Object.<anonymous> (/home/dinosaur/.nvm/versions/node/v8.2.1/lib/node_modules/scuttlebot/bin.js:57:32)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

i'm also reminded of https://github.com/ssbc/scuttlebot/pull/417, what's up with that?

**Comment by mmckegg** [comment]
I think we resolved to just remove the default private module from scuttlebot. 

Patchfoo might use it, but since ssb-private (the package) is fully backwards compatible, it should just work if that is installed. 

cc @dominictarr @clehner

**Comment by dominictarr** [comment]
I'd like to remove it from scuttlebot if but we'll need to add that directly into patchfoo or patchfoo installations will need to also run ssb-private.
